package com.example.gkdai.ai.rulegen

// Represents a GKD rule that can be dynamically generated by the AI.
// This structure aims to be compatible with GKD's internal rule structures.
data class DynamicRuleDefinition(
    val id: String, // App ID (e.g., "com.tencent.mm")
    val name: String, // App Name (e.g., "微信")
    val groups: List<DynamicGroup>,
    // Potentially other fields like enable, priority etc.
)

data class DynamicGroup(
    val key: Int,
    val name: String,
    val fastQuery: Boolean = false,
    val matchTime: Int = 10000,
    val actionMaximum: Int = 1,
    val resetMatch: String = "app", // "app" or "screen"
    val rules: List<DynamicRule>,
    // Other group fields
)

data class DynamicRule(
    val action: String, // e.g., "clickCenter", "click", "back"
    val matches: List<String>, // CSS-like selectors (e.g., "#skip_button", "[text='跳过']"
    val actionCd: Int? = null,
    val actionDelay: Int? = null,
    // Other rule fields
)
